config/routes.rb
Rails.application.routes.draw do
  root 'pets#index'
  resources :pets, :owners, :ownerships, :toys, :shirts, except:[:show]
end

app/models/owner.rb
class Owner < ActiveRecord::Base
  validates_presence_of :first_name, :last_name
  before_save :capitalize_first_name, :capitalize_last_name
  has_many :ownerships
  has_many :pets, through: :ownerships
  accepts_nested_attributes_for :ownerships

  def capitalize_first_name
    self.first_name = self.first_name.capitalize
  end

  def capitalize_last_name
    self.last_name = self.last_name.capitalize
  end
end

app/models/ownership.rb
class Ownership < ActiveRecord::Base
  belongs_to :owner, dependent: :destroy
  belongs_to :pet, dependent: :destroy
end

app/models/pet.rb
class Pet < ActiveRecord::Base
  validates_presence_of :name
  before_save :capitalize_name, :capitalize_type
  has_many :ownerships
  has_many :owners, through: :ownerships
  has_many :toys
  has_and_belongs_to_many :shirts

  def capitalize_name
    self.name = self.name.capitalize
  end

  def capitalize_type
    self.pet_type = self.pet_type.capitalize
  end

  def display_owners
    self.owners.each do |owner|
      puts owner.first_name
    end
  end
end

app/models/shirt.rb
class Shirt < ActiveRecord::Base
  has_and_belongs_to_many :pets
  accepts_nested_attributes_for :pets
end

app/models/toy.rb
class Toy < ActiveRecord::Base
  before_save :capitalize_name, :capitalize_color
  belongs_to :pet

  def capitalize_name
    self.name = self.name.capitalize
  end
  
  def capitalize_color
    self.color = self.color.capitalize
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/owners_controller.rb
class OwnersController < ApplicationController
  def index
    @owners = Owner.all.order(id: :asc)
  end

  def new
    @owner = Owner.new
    @pets = Pet.all
    2.times {@owner.ownerships.build}
  end

  def create
    @owner = Owner.new(owner_params)
    
    if @owner.save
      redirect_to owners_url
    else
      render :new
    end
  end

  def show
  end

  def edit
    @owner = Owner.find(params[:id])
  end

  def update
    @owner = Owner.find(params[:id])
    @owner.update_attributes(params[:owner].permit(:first_name, :last_name, :gender))

    respond_to do |f|
      f.html {redirect_to owners_url}
    end
  end

  def destroy
    @owner = Owner.find(params[:id])
    @owner.delete

    respond_to do |f|
      f.html {redirect_to owners_url}
    end
  end

  private
  def owner_params
    params.require(:owner).permit(:first_name, :last_name, :gender, ownerships_attributes: [:pet_id])
  end
end

app/controllers/ownerships_controller.rb
class OwnershipsController < ApplicationController
  def index
    @ownerships = Ownership.all.order(pet_id: :asc)
  end

  def new
    @ownership = Ownership.new
    @owners = Owner.all
    @pets = Pet.all
  end
  
  def create
    @ownership = Ownership.new(ownership_params)
    @ownership.save
    if @ownership.save
      redirect_to root_url
    else
      @owners = Owner.all
      @pets = Pet.all
      render :new
    end
  end

  def edit
    @ownership = Ownership.find(params[:id])
    @owners = Owner.all
    @pets = Pet.all
  end

  def update
    @ownership = Ownership.find(params[:id])
    @ownership.update_attributes(params[:ownership].permit(:owner_id, :pet_id))

    respond_to do |f|
      f.html {redirect_to root_url}
    end
  end

  def destroy
    @ownership = Ownership.find(params[:id])
    @ownership.delete

    respond_to do |f|
      f.html {redirect_to pets_url}
    end
  end

  private
  def ownership_params
    params.require(:ownership).permit(:owner_id, :pet_id)
  end
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
  def index
    @pets = Pet.all.order(id: :asc)
  end

  def new
    @pet = Pet.new
  end
  
  def create
    @pet = Pet.new(pet_params)
    if @pet.save
      redirect_to root_url
    else
      render :new
    end
  end

  def show
    @pet = Pet.find(params[:id])
  end

  def edit
    @pet = Pet.find(params[:id])
  end

  def update
    @pet = Pet.find(params[:id])
    @pet.update_attributes(params[:pet].permit(:name, :age, :pet_type))

    respond_to do |f|
      f.html {redirect_to pets_url}
    end
  end

  def destroy
    @pet = Pet.find(params[:id])
    @pet.delete

    respond_to do |f|
      f.html {redirect_to pets_url}
    end
  end

  private
  def pet_params
    params.require(:pet).permit(:name, :age, :pet_type)
  end
end

app/controllers/pets_controllers.rb
class PetsController < ApplicationController
  def index
    Pet.all
  end

  def new
    @pet = Pet.new(pet_params)
  end
  
  def create
    @pet = Pet.create(pet_params)
  end

  def show
    @pet = Pet.find(params[:id])
  end

  def edit
    @pet = Pet.find(params[:id])
  end

  def update
    @pet = Pet.find(params[:id])
    @pet.update_attributes(params[:pet].permit(:name, :age, :type)
  end

  def destroy
    @pet = Pet.find(params[:id]
    @pet.delete
  end

  private
  def pet_params
    params.require(:pet).permit(:name, :age, :type)
  end
end

app/controllers/shirts_controller.rb
class ShirtsController < ApplicationController
  def index
    @shirts = Shirt.all
  end

  def new
    @shirt = Shirt.new
    @pets = Pet.all
    3.times {@shirt.pets.build}
  end

  def create
    @shirt = Shirt.new(shirt_params)
    if params[:pet_id1] && params[:pet_id2] && params[:pet_id3] != ""
      pets = Pet.find(params[:pet_id1], params[:pet_id2], params[:pet_id3])
      @shirt.pets << pets
    elsif params[:pet_id1] && params[:pet_id2] != ""
      pets = Pet.find(params[:pet_id1], params[:pet_id2])
      @shirt.pets << pets
    elsif params[:pet_id1] != ""
      pet = Pet.find(params[:pet_id1])
      @shit.pet << pet
    end
    if @shirt.save
      redirect_to pets_url
    else
       render :new
    end
  end

  def edit
    @shirt = Shirt.find(params[:id])
  end

  def update
    @shirt = Shirt.find(params[:id])
    @shirt.update(params[:pet].permit(:color))

    respond_to do |f|
      f.html {reidrect_to pets_url}
    end
  end

  def destroy
    @shirt = Shirt.find(params[:id])
    @shirt.delete

    respond_to do |f|
      f.html {redirect_to pets_url}
    end
  end

  private
  def shirt_params
    params.require(:shirt).permit(:color)
  end
end

app/controllers/toys_controller.rb
class ToysController < ApplicationController
  def index
    @toys = Toy.all.order(pet_id: :asc)
  end

  def new
    @toy = Toy.new
    @pets = Pet.all
  end

  def create
    @toy = Toy.new(toy_params)

    if @toy.save 
      redirect_to toys_url
    else
      render :new
    end
  end

  def edit
    @toy = Toy.find(params[:id])
    @pets = Pet.all
  end

  def update
    @toy = Toy.find(params[:id])
    @toy.update_attributes(params[:toy].permit(:name, :color, :pet_id))

    respond_to do |f|
      f.html {redirect_to toys_url}
    end
  end

  def destroy
    @toy = Toy.find(params[:id])
    @toy.delete

    respond_to do |f|
      f.html {redirect_to toys_url}
    end
  end

  private
  def toy_params
    params.require(:toy).permit(:name, :color, :pet_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PetsApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/owners/edit.html.erb
<div class="container">
  <h1>Edit Owner</h1>
  <%= form_for @owner, html: {class: 'form-horizontal col-sm-4'} do |f| %>
    <div class="form-group">
      <%= f.label :first_name, 'First Name', class: 'col-sm-4' %>
      <div class="col-sm-8">
        <%= f.text_field :first_name, class: 'form-control' %>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :last_name, 'Last Name', class:'col-sm-4' %>
      <div class="col-sm-8">
        <%= f.text_field :last_name, class: 'form-control' %>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :gender, class: 'col-sm-4' %>
      <div class="col-sm-8">
        <%= f.select(:gender, ['Female', 'Male'], {include_blank: ''}, {class: 'form-control'}) %>
      </div>
    </div>
    <%= f.submit 'Edit owner', class: 'btn btn-primary pull-right' %>
  <% end %>
</div>

app/views/owners/index.html.erb
<div class="container">
  <h1>Owners List</h1>
  <nav class="nav nav-pills pull-right">
    <li role="presentation" class="active"><%= link_to 'Owners', owners_url %></li>
    <li role="presentation"><%= link_to 'Ownerships', ownerships_url %></li>
    <li role="presentation"><%= link_to 'Pets', pets_url %></li>
    <li role="presentation"><%= link_to 'Toys', toys_url %></li>
  </nav>
  <div class="col-sm-12 text-right">
    <%= link_to 'Add owner', new_owner_url %>
  </div>
  <table class="table table-striped">
    <tr>
      <th>Id#</th>
      <th>First name</th>
      <th>Last name</th>
      <th>Gender</th>
      <th>Pets</th>
      <th></th>
      <th></th>
    </tr>
    <% @owners.each do |owner| %>
      <tr>
        <td><%= owner.id %></td>
        <td><%= owner.first_name %></td>
        <td><%= owner.last_name %></td>
        <td><%= owner.gender %></td>
        <td><%= owner.pets.map{|pet| pet.name}.to_sentence %></td>
        <td><%= link_to 'Edit', [:edit, owner] %></td>
        <td><%= link_to 'Delete', owner, method: :delete %></td>
      </tr>
    <% end %>
  </table>
</div>

app/views/owners/new.html.erb
<div class="container">
  <h1>New Owner</h1>
  <%= form_for @owner, html: {class: 'form-horizontal col-sm-4'} do |f| %>
    <% if @owner.errors.any? %>
      <ul>
        <% @owner.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    <% end %>
    <div class="form-group">
      <%= f.label :first_name, 'First Name', class: 'col-sm-4' %>
      <div class="col-sm-8">
        <%= f.text_field :first_name, class: 'form-control' %>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :last_name, 'Last Name', class:'col-sm-4' %>
      <div class="col-sm-8">
        <%= f.text_field :last_name, class: 'form-control' %>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :gender, class: 'col-sm-4' %>
      <div class="col-sm-8">
        <%= f.select(:gender, ['Female', 'Male'], {include_blank: ''}, {class: 'form-control'}) %>
      </div>
    </div>
    <div class="form-group">
      <p class="col-sm-4"><b>Pets</b></p>
        <%= f.fields_for :ownerships do |builder| %>
          <%= builder.collection_select :pet_id, @pets, :id, :name, include_blank: true %>
        <% end %>
    </div>
    <%= f.submit 'Add owner', class: 'btn btn-primary pull-right' %>
  <% end %>
</div>

app/views/ownerships/edit.html.erb
<div class="container">
  <h1>Edit ownership</h1>
  <%= form_for @ownership do |f| %>
    <p><%= f.collection_select :owner_id, @owners, :id, :first_name %><p>
    <p>owns</p>
    <p><%= f.collection_select :pet_id, @pets, :id, :name %></p>
    <%= f.submit 'Update ownership', class: 'btn btn-primary' %>
  <% end %>
</div>

app/views/ownerships/index.html.erb
<div class="container">
  <h1>Ownerships List</h1>
  <nav class="nav nav-pills pull-right">
    <li role="presentation"><%= link_to 'Owners', owners_url %></li>
    <li role="presentation" class="active"><%= link_to 'Ownerships', ownerships_url %></li>
    <li role="presentation"><%= link_to 'Pets', pets_url %></li>
    <li role="presentation"><%= link_to 'Toys', toys_url %></li>
  </nav>
  <div class="col-sm-12 text-right">
    <%= link_to 'Add ownership', new_ownership_url %>
  </div>
  <table class="table table-striped">
    <tr>
      <th>Id#</th>
      <th>Owner</th>
      <th>Pet</th>
      <th></th>
      <th></th>
    </tr>
    <% @ownerships.each do |ownership| %>
      <tr>
        <td><%= ownership.id %></td>
        <td><%= ownership.owner.first_name %></td>
        <td><%= ownership.pet.name %></td>
        <td><%= link_to 'Edit', [:edit, ownership] %></td>
        <td><%= link_to 'Delete', ownership, method: :delete %></td>
      </tr>
    <% end %>
  </table>
</div>

app/views/ownerships/new.html.erb
<div class="container">
  <h1>Ownership</h1>
  <%= form_for @ownership do |f| %>
    <p><%= f.collection_select :owner_id, @owners, :id, :first_name %><p>
    <p>owns</p>
    <p><%= f.collection_select :pet_id, @pets, :id, :name %></p>
    <%= f.submit 'Create ownership', class: 'btn btn-primary' %>
  <% end %>
</div>

app/views/pets/edit.html.erb
<div class="container">
  <h1>Edit Pet</h1>
  <%= form_for @pet, html: {class: 'form-horizontal col-sm-4'} do |f| %>
    <% if @pet.errors.any? %>
      <ul>
        <% @pet.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
      </ul>
    <% end %>
    <div class="form-group">
      <%= f.label :name, class: 'col-sm-2 control-label' %>
      <div class="col-sm-10">
        <%= f.text_field :name, class: 'form-control' %>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :age, class: 'col-sm-2 control-label' %>
      <div class="col-sm-10">
        <%= f.text_field :age, class: 'form-control' %>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :pet_type, 'Type', class: 'col-sm-2 control-label' %>
      <div class="col-sm-10">
        <%= f.text_field :pet_type, class: 'form-control' %>
      </div>
    </div>
    <%= f.submit 'Update pet', class: 'btn btn-primary pull-right' %>
  <% end %>
</div>

app/views/pets/index.html.erb
<div class="container">
  <h1>Jingling Gate Pets</h1>
  <nav class="nav nav-pills pull-right">
    <li role="presentation"><%= link_to 'Owners', owners_url %></li>
    <li role="presentation"><%= link_to 'Ownerships', ownerships_url %></li>
    <li role="presentation" class="active"><%= link_to 'Pets', pets_url %></li>
    <li role="presentation"><%= link_to 'Toys', toys_url %></li>
  </nav>
  <div class="col-sm-12 text-right"><%= link_to 'Add pet', new_pet_url%></div>
  <table class="table table-striped">
    <tr>
      <th>Id#</th>
      <th>Name</th>
      <th>Age</th>
      <th>Type</th>
      <th>Owners</th>
      <th>Toys</th>
      <th></th>
      <th></th>
    </tr>
    <% @pets.each do |p| %>
      <tr>
        <td><%= p.id %></td>
        <td><%= p.name %></td>
        <td><%= p.age %></td>
        <td><%= p.pet_type %></td>
        <td><%= p.owners.map{|o| o.first_name}.to_sentence %></td>
        <td><%= p.toys.map{|t| t.name}.to_sentence %></td>
        <td><%= link_to 'Edit', [:edit, p] %></td>
        <td><%= link_to 'Delete', p, method: :delete %></td>
      </tr>
    <% end %>
  </table>

</div>

app/views/pets/new.html.erb
<h1>New Pet</h1>
<%= form_for @pet do |f| %>
  <% if @pet.errors.any? %>
    <ul>
      <% @pet.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
    </ul>
  <% end %>
  <div><%= f.label :name %></div>
  <div><%= f.text_field :name %></div>
  <div><%= f.label :age %></diV>
  <div><%= f.text_field :age %></div>
  <div><%= f.label :type %></div>
  <div><%= f.text_field :type %></div>
  <div><%= f.submit 'Add pet' %></div>
<% end %>

app/views/shirts/index.html.erb
<div class="container">
  <h1>Shirts list</h1>
</div>

app/views/shirts/new.html.erb
<div class="container">
  <h1>New shirt</h1>
  <%= form_for @shirt, html: {class: 'form-horizontal col-sm-4'} do |f| %>
    <div class="form-group">
      <%= f.label :color, class: 'col-sm-4' %>
      <div class="col-sm-8">
        <%= f.text_field :color, class:'form-control' %>
      </div>
    </div>
    <!--<#% f.fields_for :pets do |builder| %>
      <div class="from-group">
        <#%= builder.label :name %>
        <#%= builder.collection_select :pet_id, @pets, :id, :name, rows: 3 %>
      </div>
    <#% end %>--> 
    <div class="form-group">
      <div class="col-sm-4">
        <b>Pets</b>
      </div>
      <div class="col-sm-4">
        <%= select_tag 'pet_id1', options_for_select(@pets.collect{ |p| [p.name, p.id]}), include_blank: true %>
      </div>
    </div>
    <div class="form-group">
      <div class="col-sm-4 col-sm-offset-4">
        <%= select_tag 'pet_id2', options_for_select(@pets.collect{ |p| [p.name, p.id]}), include_blank: true %>
      </div>
    </div>
    <div class="form-group">
      <div class="col-sm-4 col-sm-offset-4">
        <%= select_tag 'pet_id3', options_for_select(@pets.collect{ |p| [p.name, p.id]}), include_blank: true %>
      </div>
    </div>
    <%= f.submit 'Add shirt', class:'btn btn-primary pull-right' %>
  <% end %>
</div>

app/views/toys/edit.html.erb
<div class="container">
  <h1>Edit toy</h1>
  <%= form_for @toy, html: {class: 'form-horizontal col-sm-4'} do |f| %>
    <div class="form-group">
      <%= f.label :name, 'Type', class:'col-sm-4' %>
      <div class="col-sm-8">
        <%= f.text_field :name, class:'form-control' %>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :color, class:'col-sm-4' %>
      <div class="col-sm-8">
        <%=f.text_field :color, class:'form-control' %>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :pet_id, 'Belongs to pet', class:'col-sm-6' %>
      <%= f.collection_select :pet_id, @pets, :id, :name %>
    </div>
    <%= f.submit 'Update toy', class:'btn btn-primary pull-right' %>
  <% end %>
</div>

app/views/toys/index.html.erb
<div class="container">
  <h1>Toys list</h1>
  <nav class="nav nav-pills pull-right">
    <li role="presentation"><%= link_to 'Owners', owners_url %></li>
    <li role="presentation"><%= link_to 'Ownerships', ownerships_url %></li>
    <li role="presentation"><%= link_to 'Pets', pets_url %></li>
    <li role="presentation" class="active"><%= link_to 'Toys', toys_url %></li>
  </nav>
  <div class="col-sm-12 text-right">
    <%= link_to 'Add toy', new_toy_url %>
  </div>
  <table class="table table-striped">
    <tr>
      <th>Id#</th>
      <th>Type</th>
      <th>Color</th>
      <th>Belongs to pet</th>
      <th></th>
      <th></th>
    </tr>
    <% @toys.each do |t| %>
      <tr>
        <td><%= t.id %></td>
        <td><%= t.name %></td>
        <td><%= t.color %></td>
        <td><%= t.pet.name %></td>
        <td><%= link_to 'Edit', [:edit, t]%></td>
        <td><%= link_to 'Delete', t, method: :delete %></td>
      </tr>
    <% end %>
  </table>
</div>

app/views/toys/new.html.erb
<div class="container">
  <h1>New toy</h1>
  <%= form_for @toy, html: {class: 'form-horizontal col-sm-4'} do |f| %>
    <div class="form-group">
      <%= f.label :name, 'Type', class:'col-sm-4' %>
      <div class="col-sm-8">
        <%= f.text_field :name, class:'form-control' %>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :color, class:'col-sm-4' %>
      <div class="col-sm-8">
        <%=f.text_field :color, class:'form-control' %>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :pet_id, 'Belongs to pet', class:'col-sm-6' %>
      <%= f.collection_select :pet_id, @pets, :id, :name %>
    </div>
    <%= f.submit 'Create toy', class:'btn btn-primary pull-right' %>
  <% end %>
</div>